# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='category',
            field=models.ManyToManyField(null=True, to='gallery.categories'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='location_taken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Location'),
        ),
    ]
