# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180121_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='category',
            field=models.ManyToManyField(to='gallery.categories'),
        ),
    ]
